### ISSUE TITLE
delocate fails in Sierra

### ISSUE THREAD

**Issue by kozo2** [ecell/ecell4-wheels#1]
```
bash-3.2$ ~/Library/Python/2.7/bin/delocate-listdeps --all python/dist/ecell-4.0.4-cp27-cp27m-macosx_10_12_intel.whl 
Traceback (most recent call last):
  File "/Users/knishida/Library/Python/2.7/bin/delocate-listdeps", line 61, in <module>
    main()
  File "/Users/knishida/Library/Python/2.7/bin/delocate-listdeps", line 44, in main
    lib_dict = wheel_libs(path)
  File "/Users/knishida/Library/Python/2.7/lib/python/site-packages/delocate/libsana.py", line 161, in wheel_libs
    lib_dict = tree_libs(tmpdir, filt_func)
  File "/Users/knishida/Library/Python/2.7/lib/python/site-packages/delocate/libsana.py", line 54, in tree_libs
    for install_name in get_install_names(depending_libpath):
  File "/Users/knishida/Library/Python/2.7/lib/python/site-packages/delocate/tools.py", line 166, in get_install_names
    out = back_tick(['otool', '-L', filename])
  File "/Users/knishida/Library/Python/2.7/lib/python/site-packages/delocate/tools.py", line 58, in back_tick
    cmd_str, retcode, err.decode('latin-1')))
RuntimeError: otool -L /private/var/folders/l9/0ngq1rx57kq46wcysykycblr0000gn/T/tmpU7Go9f/ecell-4.0.4.data/data/ecell4-licenses/hdf5.txt returned code 1 with error /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/private/var/folders/l9/0ngq1rx57kq46wcysykycblr0000gn/T/tmpU7Go9f/ecell-4.0.4.data/data/ecell4-licenses/hdf5.txt': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed

```

**Comment by kozo2** [comment]
`pip install ecell-4.0.4-cp27-cp27m-macosx_10_12_intel.whl` did not fail and the E-Cell worked in Sierra.
